/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.yammy;
import java.awt.CardLayout;
import java.sql.*;
import java.util.ArrayList;
import java.awt.Component;
/**
 *
 * @author Asher
 */
public class browse_page extends javax.swing.JPanel {

    /**
     * Creates new form browse_page
     */
    
    ArrayList<String> ingredients=new ArrayList<String>();
    public void display_recipes(){
        
        
        for(Component c:this.getComponents()){//Clear the current recipes
            if(c instanceof recipe_block){
                this.remove(c);
                System.out.println(c+" removed");
            } 
            
        }
        for(Component c:main_frame.mf.getContentPane().getComponents()){
            if(c instanceof recipe_page){
                main_frame.mf.getContentPane().remove(c);
                System.out.println(c+" removed");
            }
        }

        // TODO : get recipes from the database and display it.
        String ingredient_list_string=new String("");
        for(int i=0;i<ingredients.size();++i){ //Combine the elemts in the ingredients array for passing it in the query.
            ingredient_list_string+=String.format("'%s'", ingredients.get(i));
            if(i!=ingredients.size()-1){
                ingredient_list_string+=",";
            }
        }
//        System.out.println(ingredient_list_string);
        String query="";
        if(!ingredients.isEmpty()){
            query=String.format("select distinct Recipe.recipe_id,recipe_name,recipe_body from recipe,recipe_ingredients,ingredient where recipe.recipe_id=recipe_ingredients.recipe_id and ingredient.ingredient_id=recipe_ingredients.ingredient_id and ingredient.ingredient_name in (%s);", ingredient_list_string);
        }else{
            query="select * from recipe";
        }
        System.out.println(query);
        Connection conn=Yammy.conn;
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            int columnsNumber=rs.getMetaData().getColumnCount();
            int i=0;
            while (rs.next()) {
                
                System.out.println(rs.getString("recipe_name"));
                System.out.println(rs.getString("recipe_body"));
                recipe_block rb=new recipe_block(rs.getString("recipe_name"),rs.getString("recipe_body"));
                rb.setBounds(150,300+(i*120),rb.getMaximumSize().width,rb.getMaximumSize().height);
                this.add(rb);
                
                System.out.println(rb+" added");
                i++;
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
        this.repaint();
        this.validate();
    }
    public browse_page() {
        initComponents();
        display_recipes();
        this.validate();
        this.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Browse Recipes");
        add(jLabel1);
        jLabel1.setBounds(352, 6, 255, 77);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/yammy/home_icon.png"))); // NOI18N
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(23, 28, 36, 37);

        jLabel4.setText("Ingredients  : ");
        add(jLabel4);
        jLabel4.setBounds(240, 150, 71, 16);

        jButton2.setText("Add Ingredient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(660, 170, 150, 38);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(240, 170, 400, 40);

        jLabel2.setText("Search Based on the ingredients you gave");
        add(jLabel2);
        jLabel2.setBounds(360, 110, 240, 16);
        add(jLabel3);
        jLabel3.setBounds(320, 150, 470, 20);

        jButton4.setText("Clear Ingredients");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(820, 150, 130, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ingredients.add(jTextField1.getText());
        jTextField1.setText("");
        jLabel3.setText(String.join(" , ", ingredients));
        display_recipes();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.getParent().getLayout();
        layout.show(this.getParent(), "starting_page");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ingredients.clear();
        display_recipes();
        jLabel3.setText(String.join(" , ", ingredients));
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
