/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.yammy;
import java.awt.CardLayout;
/**
 *
 * @author Asher
 */
public class browse_page extends javax.swing.JPanel {

    /**
     * Creates new form browse_page
     */
    private void display_recipes(){
        recipe_block rb1=new recipe_block("Recipe 1","recipe body 1");
        recipe_block rb2=new recipe_block("Recipe 2","recipe body 2");
        rb1.setBounds(130,300,rb1.getMaximumSize().width,rb1.getMaximumSize().height);
        this.add(rb1);
        rb2.setBounds(130,500,rb2.getMaximumSize().width,rb2.getMaximumSize().height);
        this.add(rb2);
        // TODO : get recipes from the database and display it.
    }
    public browse_page() {
        initComponents();
        display_recipes();
        this.validate();
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Browse Recipes");
        add(jLabel1);
        jLabel1.setBounds(352, 6, 255, 77);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/yammy/home_icon.png"))); // NOI18N
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(23, 28, 36, 37);

        jLabel4.setText("Ingredients : ");
        add(jLabel4);
        jLabel4.setBounds(250, 150, 68, 16);

        jButton2.setText("Add Ingredient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(690, 170, 100, 38);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(240, 170, 400, 40);

        jLabel2.setText("Search Based on the ingredients you gave");
        add(jLabel2);
        jLabel2.setBounds(360, 110, 240, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.getParent().getLayout();
        layout.show(this.getParent(), "starting_page");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
