/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.yammy;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Component;
/**
 *
 * @author Asher
 */
public class calorie_page extends javax.swing.JPanel {
    
    int min_calorie=0;
    int max_calorie=10000;
    private void display_recipes(){
        
        // TODO : get recipes from the database and display it.
        
        String query=new String("");
        
        if(!"".equals(jTextField1.getText()) || !"".equals(jTextField2.getText())){
            min_calorie=Integer.parseInt(jTextField1.getText());
            max_calorie=Integer.parseInt(jTextField2.getText());
            
        }
       
        query=String.format("select * from recipe where calorie_content>=%d and calorie_content<=%d;", min_calorie,max_calorie);
        System.out.println(query);
        Connection conn=Yammy.conn;
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            int columnsNumber=rs.getMetaData().getColumnCount();
            int i=0;
            while (rs.next()) {
                
                System.out.println(rs.getString("recipe_name"));
                System.out.println(rs.getString("recipe_body"));
                recipe_block rb=new recipe_block(rs.getString("recipe_name"),rs.getString("recipe_body"));
                rb.setBounds(150,300+(i*120),rb.getMaximumSize().width,rb.getMaximumSize().height);
                this.add(rb);
                
                System.out.println(rb+" added");
                i++;
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
        this.repaint();
        this.validate();
    }

    /**
     * Creates new form calorie_page
     */
    public calorie_page() {
        initComponents();
        display_recipes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Calorie Tracking");
        add(jLabel1);
        jLabel1.setBounds(349, 6, 265, 77);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/yammy/home_icon.png"))); // NOI18N
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(20, 24, 36, 37);

        jLabel2.setText("Enter your Minimum calorie");
        add(jLabel2);
        jLabel2.setBounds(242, 110, 150, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(410, 107, 144, 22);

        jLabel3.setText("Enter your Maximum calorie");
        add(jLabel3);
        jLabel3.setBounds(242, 144, 150, 16);
        add(jTextField2);
        jTextField2.setBounds(410, 141, 144, 22);

        jButton2.setText("Apply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(660, 120, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.getParent().getLayout();
        layout.show(this.getParent(), "starting_page");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for(Component c:this.getComponents()){
            if(c instanceof recipe_block){
                this.remove(c);
            }
        }
        display_recipes();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
